import type { Metadata } from "next"
import Link from "next/link"
import { CaseStudyGrid, ContactActions, ConversionPanel, ReviewGrid, SectionHeading, TrustStrip } from "@/components/marketing"
import { pageMetadata } from "@/lib/site"

export const metadata: Metadata = pageMetadata(
  "About NOX Fire & Security | Built in Chesterfield",
  "Discover how NOX combines a local Chesterfield approach with the experience and professional standards required for homes, commercial premises, industrial sites and multi-site projects.",
  "/about-us",
  { image: "/images/projects/logo-nox-fire-security.jpg", imageAlt: "NOX Fire and Security logo" },
)

export default function AboutPage() {
  return <div className="about-page">
    <section className="about-hero-premium about-hero-editorial"><div className="container about-hero-grid"><div><span className="eyebrow">About NOX</span><h1>Built in Chesterfield. Professional standards at every scale.</h1><p className="lead">NOX combines the accountability and personal service of a local business with the experience, planning and delivery expected across commercial, industrial and multi-site projects.</p><ContactActions primaryLabel="Discuss Your Requirements" /></div><div className="about-brand-panel"><img src="/images/projects/logo-nox-fire-security.jpg" alt="NOX Fire & Security logo mark"/><span>Chesterfield · Sheffield · Derbyshire</span><blockquote>Designed properly.<br/>Installed properly.<br/>Supported properly.</blockquote></div></div></section>
    <TrustStrip variant="general"/>

    <section className="section about-story-section"><div className="container about-origin-grid">
      <div><span className="eyebrow">Why NOX was founded</span><h2>Local roots. Commercial capability.</h2></div>
      <div className="about-long-copy">
        <p>NOX Fire & Security was founded in Chesterfield to provide a more considered approach to fire and security—one built around the property, the people using it and the level of protection genuinely required.</p>
        <p>After gaining experience within the national security industry, Joseph and James saw how capable technology could be let down by rigid packages, disconnected departments and systems designed around a sales process rather than the customer.</p>
        <p>NOX was created to work differently. We take the time to understand the site, identify the risks and recommend a system with a clear purpose behind every part of the design.</p>
        <p>Being built in Chesterfield means our reputation within the local community matters. Every survey, installation and service visit contributes to the relationships and recommendations the business has grown through.</p>
        <p>From the initial survey and quotation through to installation, certification, servicing and future upgrades, each project remains connected and accountable. Customers deal with the same business throughout, with clear communication and continued support after the installation is complete.</p>
        <p>Today, NOX supports homeowners, commercial premises, industrial sites, landlords and multi-site organisations across Derbyshire and South Yorkshire. As the business has grown, so has the experience and structure needed to deliver larger and phased projects professionally. Whether completing a single installation or coordinating work across several locations, the approach remains the same: sensible design, professional delivery and a long-term relationship built on trust.</p>
      </div>
    </div></section>

    <section className="section section-alt"><div className="container"><SectionHeading eyebrow="Our journey" title="Built step by step around connected responsibility" text="NOX has developed its services around what customers need before, during and after installation—not around rigid packages or unnecessary contracts."/><div className="journey-editorial journey-editorial-detailed">
      <article><span>01</span><div><h3>Experience inside the security industry</h3><p>Joseph developed his background in consultations, sales leadership and client relationships, while James built his technical and operational experience around installations, system quality and project delivery. Together they saw where commercial planning, installation and aftercare could become disconnected.</p></div></article>
      <article><span>02</span><div><h3>NOX is founded in Chesterfield</h3><p>The company began with a clear principle: every system should be designed around the property. Residential alarms, CCTV and commercial security projects were approached with honest advice, considered equipment selection and a cleaner, more accountable installation experience.</p></div></article>
      <article><span>03</span><div><h3>Fire, monitoring and annual support become part of the model</h3><p>Customers needed help beyond the original installation. NOX expanded into fire alarm work, emergency lighting, professional monitoring, maintenance, takeovers and system upgrades so the same business could remain involved throughout the life of the equipment.</p></div></article>
      <article><span>04</span><div><h3>A long-term regional Fire & Security partner</h3><p>Today NOX supports homes, showrooms, warehouses, industrial sites, hospitality premises, landlords and larger commercial customers across Chesterfield, Sheffield, Derbyshire and South Yorkshire. The business remains locally accountable, personally involved and focused on long-term client relationships.</p></div></article>
    </div></div></section>

    <section className="section leadership-section"><div className="container"><SectionHeading eyebrow="Clear responsibility" title="Meet the Founders" text="Joseph and James remain closely involved from the first conversation through to installation and ongoing support. Each leads a defined area of the business, providing clear responsibility across commercial planning, system delivery and aftercare."/>
      <div className="founder-profile-grid">
        <article className="founder-profile"><div className="founder-profile-image"><img src="/images/joseph-robb.jpeg" alt="Joseph Robb, Co-Founder and Managing Director at NOX Fire and Security"/></div><div><span className="team-role">Joseph Robb</span><h2>Co-Founder &amp; Managing Director</h2><p className="founder-remit">Commercial direction, system proposals and client relationships</p><p>Joseph leads the commercial direction of NOX and oversees surveys, quotations, system proposals, business development, finance and marketing.</p><p>His role begins by understanding the property, how it is used, the risks involved and what the customer wants the system to achieve. From there, he develops a clear proposal designed around the site rather than forcing the customer into a predetermined package.</p><p>Joseph also manages commercial relationships and larger project opportunities, ensuring the scope, pricing and delivery plan remain clear from the initial consultation through to completion. His focus is on straightforward advice, sensible solutions and building relationships that continue through servicing, monitoring and future upgrades.</p></div></article>
        <article className="founder-profile"><div className="founder-profile-image"><img src="/images/james-rigby.webp" alt="James Rigby, Co-Founder and Operations Director at NOX Fire and Security"/></div><div><span className="team-role">James Rigby</span><h2>Co-Founder &amp; Operations Director</h2><p className="founder-remit">Operations, technical delivery and fire systems</p><p>James leads the operational and technical delivery of NOX projects. He is responsible for installation standards, equipment preparation, project planning, stock, certification, technical guidance, servicing and aftercare.</p><p>From confirming the final design through to installation, testing and handover, James ensures every system is delivered correctly and performs as intended. His focus is on sensible device positioning, clean presentation, reliable operation and a finished installation that reflects what was agreed during the consultation.</p><p>James also leads the continued development and delivery of NOX’s fire alarm and compliance services, while remaining responsible for technical support, fault resolution and the ongoing performance of installed systems.</p></div></article>
      </div>
    </div></section>

    <section className="section section-alt"><div className="container"><SectionHeading eyebrow="How we work" title="Commercial capability with local accountability"/><div className="about-editorial-columns">
      <article><span>Property first</span><h3>The system is designed before the equipment list is finalised.</h3><p>Access points, routines, appearance, existing equipment, future support and the way the property is actually used all influence the proposal. Ajax is the preferred smart-security platform, but NOX remains free to recommend other suitable professional equipment where the property requires it.</p></article>
      <article><span>Professional delivery</span><h3>The installation is treated as part of the finished property.</h3><p>Device positions, cable routes, panel locations, app setup and final presentation are planned carefully. The handover is not rushed: users, operating modes, playback and practical next steps are explained clearly before the project is considered complete.</p></article>
      <article><span>Long-term support</span><h3>Installation should be the beginning of the relationship.</h3><p>Professional monitoring, alarm maintenance, CCTV servicing, fire alarm servicing, emergency lighting, takeovers, repairs and system development remain available through the same local business after handover.</p></article>
    </div></div></section>

    <section className="section"><div className="container"><SectionHeading eyebrow="Why customers choose NOX" title="Local accountability supported by real project evidence" text="The difference is not a claim that one product suits every property. It is a connected process, genuine workmanship and clear responsibility for the finished result."/><div className="feature-grid columns-4">
      <article className="feature-card"><span className="feature-number">01</span><h3>Clear responsibility</h3><p>Joseph and James lead commercial planning, operations and installation quality, keeping ownership clear from the first enquiry through to ongoing support.</p></article>
      <article className="feature-card"><span className="feature-number">02</span><h3>Useful, honest specification</h3><p>The proposal is shaped around the property and required outcome, with professional alternatives considered where a different platform is the better fit.</p></article>
      <article className="feature-card"><span className="feature-number">03</span><h3>Proof of completed work</h3><p>Case studies use genuine NOX photography and confirmed project details across homes, hospitality, industrial sites, estates, retail and commercial premises.</p></article>
      <article className="feature-card"><span className="feature-number">04</span><h3>Support throughout system life</h3><p>Servicing, monitoring, takeovers, repairs and upgrades provide a practical route forward after the initial installation rather than leaving the customer unsupported.</p></article>
    </div></div></section>

    <section className="section"><div className="container"><SectionHeading eyebrow="Real work" title="Residential and commercial installations by NOX" text="A selection of confirmed projects across homes, showrooms, industrial sites, estates and commercial premises."/><CaseStudyGrid limit={6}/><div className="button-row"><Link className="button button-outline" href="/case-studies">View All Case Studies</Link></div></div></section>
    <section className="section section-alt"><div className="container"><SectionHeading eyebrow="Customer reviews" title="What customers say about the NOX experience"/><ReviewGrid names={["Sasha Brailsford", "Jez S", "Rory Stirland"]}/><div className="button-row"><Link className="button button-outline" href="/reviews">Read More Reviews</Link></div></div></section>
    <ConversionPanel title="Discuss your property with NOX" text="Tell us what you want to protect or which system needs attention. We will review the details and confirm the survey, quotation or servicing next step."/>
  </div>
}
