import type { Metadata } from "next"
import Link from "next/link"
import { CaseStudyGrid, ContactActions, ConversionPanel, ReviewGrid, SectionHeading, TrustStrip } from "@/components/marketing"
import { pageMetadata } from "@/lib/site"

export const metadata: Metadata = pageMetadata(
  "About NOX Fire & Security | Our Story",
  "Meet the people behind NOX Fire & Security and discover the journey from security-industry experience to accountable local installation, servicing and aftercare.",
  "/about-us"
)

export default function AboutPage() {
  return <>
    <section className="about-hero-premium about-hero-editorial"><div className="container about-hero-grid"><div><span className="eyebrow">The NOX story</span><h1>A local Fire & Security company built around accountability.</h1><p className="lead">NOX was created to offer a more personal, professional alternative: understand the property properly, recommend the right system, deliver a clean installation and remain available after handover.</p><ContactActions primaryLabel="Discuss Your Requirements" /></div><div className="about-brand-panel"><img src="/images/projects/logo-nox-fire-security.jpg" alt="NOX Fire & Security logo mark"/><span>Chesterfield · Sheffield · Derbyshire</span><blockquote>Designed properly.<br/>Installed properly.<br/>Supported properly.</blockquote></div></div></section>
    <TrustStrip variant="general"/>

    <section className="section"><div className="container about-origin-grid">
      <div><span className="eyebrow">Why NOX was started</span><h2>Security should begin with the property, not a sales package.</h2></div>
      <div className="about-long-copy"><p>Joseph and James built NOX after developing their experience inside the security industry and seeing how easily excellent technology could be let down by the customer journey around it. Systems were sometimes selected too early, shaped by rigid packages or short-term sales targets before anyone had taken enough time to understand the building, the customer’s routine or the genuine level of risk.</p><p>They also saw what happened after the installation. The person who discussed the system, the engineer who fitted it and the team dealing with faults or servicing could all be disconnected. Customers often knew what equipment they had bought, but not who remained accountable for the finished result.</p><p>NOX was formed to bring those stages back together. The first conversation, site survey, quotation, installation, handover, monitoring, annual servicing and future upgrades are treated as one continuing relationship. That approach now supports homes, commercial premises, industrial sites, landlords and customers who need more than one Fire & Security service through the same local team.</p></div>
    </div></section>

    <section className="section section-alt"><div className="container"><SectionHeading eyebrow="Our journey" title="Built step by step around the needs of our customers" text="NOX has grown by adding the services customers genuinely needed after installation, not by trying to look like a national catalogue of products."/><div className="journey-editorial journey-editorial-detailed">
      <article><span>01</span><div><h3>Experience inside the security industry</h3><p>Joseph developed his background in consultations, sales leadership and customer relationships, while James built his technical and operational experience around installations, system quality and project delivery. Together they saw both sides of the customer journey and the points where it could become fragmented.</p></div></article>
      <article><span>02</span><div><h3>NOX is founded in Chesterfield</h3><p>The company began with a clear principle: every system should be designed around the property. Residential alarms, CCTV and commercial security projects were approached with honest advice, considered equipment selection and a cleaner, more personal installation experience.</p></div></article>
      <article><span>03</span><div><h3>Fire, monitoring and annual support become part of the model</h3><p>Customers needed help beyond the original installation. NOX expanded into fire alarm work, emergency lighting, professional monitoring, maintenance, takeovers and system upgrades so the same team could remain involved throughout the life of the equipment.</p></div></article>
      <article><span>04</span><div><h3>A long-term regional Fire & Security partner</h3><p>Today NOX supports homes, showrooms, warehouses, industrial sites, hospitality premises, landlords and larger commercial customers across Chesterfield, Sheffield, Derbyshire and the surrounding region. The business remains founder-led, locally accountable and focused on building long-term customer relationships.</p></div></article>
    </div></div></section>

    <section className="section leadership-section"><div className="container"><SectionHeading eyebrow="The people behind NOX" title="Direct contact with the people responsible for the standard" text="Joseph and James lead different parts of the business, but the customer experience remains connected from the first enquiry through to installation and ongoing support."/>
      <div className="founder-profile-grid">
        <article className="founder-profile"><div className="founder-profile-image"><img src="/images/joseph-robb.jpeg" alt="Joseph Robb, Co-Founder and Managing Director at NOX Fire and Security"/></div><div><span className="team-role">Joseph Robb · Co-Founder & Managing Director</span><h2>Consultations, customer strategy and business direction</h2><p>Joseph leads the direction of NOX and the customer-facing side of the business. He oversees consultations, quotations, system proposals, commercial relationships and business development. His role is to make sure the customer understands the options, the quotation reflects the property and the proposed system has a clear reason behind every important part of the design.</p><p>From a residential survey to a larger commercial opportunity, Joseph remains focused on clarity, long-term relationships and building a business customers feel comfortable returning to for monitoring, servicing, repairs and future upgrades.</p></div></article>
        <article className="founder-profile"><div className="founder-profile-image"><img src="/images/james-rigby.webp" alt="James Rigby, Co-Founder and Operations Director at NOX Fire and Security"/></div><div><span className="team-role">James Rigby · Co-Founder & Operations Director</span><h2>Operations, installation quality and Fire systems</h2><p>James leads installations, day-to-day operations, technical quality and the Fire side of NOX. He is responsible for turning the proposed design into a properly delivered project, from equipment preparation and on-site decisions through to testing, handover, servicing and fault resolution.</p><p>His focus is on the standard of the finished work: sensible device positions, clean presentation, reliable operation and an installation that matches what was promised during the consultation. James also leads the continued development of NOX’s fire alarm and compliance-support services.</p></div></article>
      </div>
    </div></section>

    <section className="section section-alt"><div className="container"><SectionHeading eyebrow="How we work" title="Modern technology supported by a more personal service"/><div className="about-editorial-columns">
      <article><span>Property first</span><h3>The system is designed before the equipment list is finalised.</h3><p>Access points, routines, appearance, existing equipment, future support and the way the property is actually used all influence the proposal. Ajax is the preferred smart-security platform, but NOX remains free to recommend other suitable professional equipment where the property requires it.</p></article>
      <article><span>Professional delivery</span><h3>The installation is treated as part of the finished property.</h3><p>Device positions, cable routes, panel locations, app setup and final presentation are planned carefully. The handover is not rushed: users, operating modes, playback and practical next steps are explained clearly before the project is considered complete.</p></article>
      <article><span>Long-term support</span><h3>Installation should be the beginning of the relationship.</h3><p>Professional monitoring, alarm maintenance, CCTV servicing, fire alarm servicing, emergency lighting, takeovers, repairs and system development remain available through the same local company after handover.</p></article>
    </div></div></section>

    <section className="section"><div className="container"><SectionHeading eyebrow="Real work" title="Residential and commercial installations by NOX" text="A selection of confirmed projects across homes, showrooms, industrial sites, estates and commercial premises."/><CaseStudyGrid limit={6}/><div className="button-row"><Link className="button button-outline" href="/case-studies">View All Case Studies</Link></div></div></section>
    <section className="section section-alt"><div className="container"><SectionHeading eyebrow="Customer reviews" title="What customers say about the NOX experience"/><ReviewGrid names={["Sasha Brailsford", "Jez S", "Rory Stirland"]}/><div className="button-row"><Link className="button button-outline" href="/reviews">Read More Reviews</Link></div></div></section>
    <ConversionPanel title="Discuss your property with NOX" text="Tell us what you want to protect or which system needs attention. We will review the details and confirm the survey, quotation or servicing next step."/>
  </>
}
